name: perpus_app
description: A Flutter library management application

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  provider: ^6.1.1
  shared_preferences: ^2.2.2

  # Network & API
  dio: ^5.4.0
  cached_network_image: ^3.3.1
  http: ^1.1.2

  # UI & Navigation
  intl: ^0.19.0
  flutter_secure_storage: ^9.0.0

  # File handling - Updated versions
  file_picker: ^8.1.2 # Update to latest version
  path_provider: ^2.1.2
  permission_handler: ^11.2.0

  # Other plugins
  url_launcher: ^6.3.1 # Also update url_launcher
  sqflite: ^2.3.0
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
